#!/usr/bin/env python3
import os
import xml.etree.ElementTree as ET

from pymatgen.core.structure import Structure

from lib import process_vasprun_decorator


def get_pymatgen_structure(poscar_path: str):
    # POSCARファイルの存在確認
    if not os.path.exists(poscar_path):
        raise FileNotFoundError(f"{poscar_path} not found.")
    # POSCARを読み込む
    try:
        return Structure.from_file(poscar_path)
    except Exception as e:
        raise RuntimeError(f"Failed to read {poscar_path}: {e}")


def get_epsilon(vasprun_path):
    # XMLファイルをパースし、そのルート要素を取得する
    root = ET.parse(vasprun_path).getroot()

    # XML構造内で誘電率テンソルを含むarray要素を取得する
    epsilon_elements = root.findall(".//varray[@name='epsilon']/v")

    # 抽出した誘電率テンソルを格納するための空リストを初期化する
    epsilon_array: list[list[float]] = []

    # epsilon_elementsから各行を取得し、floatリストに変換し、epsilon_arrayに追加する
    for element in epsilon_elements:
        epsilon_array.append(list(map(float, element.text.split())))

    # 誘電率テンソルを3x3のfloat配列として返す
    return epsilon_array


def get_born_charges(vasprun_path):
    # vasprun.xmlファイルをパースし、そのルート要素を取得する
    root = ET.parse(vasprun_path).getroot()

    # XML構造内でボルン有効電荷テンソルを含むarray要素を取得する
    born_charge_elements_array = root.findall(".//array[@name='born_charges']/set")

    # 抽出したボルン有効電荷テンソルを格納するための空リストを初期化する
    born_charges: list[list[list[float]]] = []

    # 原子ごとにループする
    # born_charge_elementsは当該原子のボルン有効電荷テンソルである
    for born_charge_elements in born_charge_elements_array:
        # 所与の原子のボルン有効電荷テンソルを格納するリストを初期化する
        born_charges.append([])

        # born_charge_elementsから各行を取得し、floatリストに変換し、初期化したリストに追加する
        for element in born_charge_elements.findall("v"):
            born_charges[-1].append(list(map(float, element.text.split())))

    # ボルン有効電荷テンソルのリストを返す。
    return born_charges


@process_vasprun_decorator("get dielectric tensor")
def main(vasprun_path: str):
    epsilon = get_epsilon(vasprun_path)
    born_charges = get_born_charges(vasprun_path)

    print("Dielectric tensor")
    for i in range(3):
        for j in range(3):
            print(f"{epsilon[i][j]:+.6f}", end=" ")
        print()
    print()

    print("Born effective charge tensor")
    for num, born_charge in enumerate(born_charges):
        print(f"Atom {num+1}")
        for i in range(3):
            for j in range(3):
                print(f"{born_charge[i][j]:+.6f}", end=" ")
            print()
        print()


if __name__ == "__main__":
    main()
