#!/usr/bin/env python3
from pymatgen.core import Structure

from lib import process_poscar_decorator


@process_poscar_decorator("get lattice parameters")
def main(poscar_path: str):
    structure = Structure.from_file(poscar_path)
    lattice = structure.lattice
    print(f"{'a':6} = {lattice.a:.4f} Å")
    print(f"{'b':6} = {lattice.b:.4f} Å")
    print(f"{'c':6} = {lattice.c:.4f} Å")
    print(f"{'alpha':6} = {lattice.alpha:.4f} degrees")
    print(f"{'beta':6} = {lattice.beta:.4f} degrees")
    print(f"{'gamma':6} = {lattice.gamma:.4f} degrees")
    print(f"{'volume':6} = {lattice.volume:.4f} Å^3")


if __name__ == "__main__":
    main()
