#!/usr/bin/env python3
import argparse

from pymatgen.io.vasp import Vasprun

from lib import get_vasprun, warn_nonconvergence


def main(vasprun: Vasprun):
    warn_nonconvergence(vasprun)
    bandgap = vasprun.complete_dos.get_gap()
    print(f"Bandgap: {bandgap} eV")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Get total energies")
    vasprun = get_vasprun(parser)
    main(vasprun)
