#!/usr/bin/env python3
from pymatgen.io.vasp import Vasprun

from lib import process_vasprun_decorator


@process_vasprun_decorator("Get bandgap")
def main(vasprun: Vasprun):
    bandgap = vasprun.complete_dos.get_gap()
    print(f"Bandgap: {bandgap} eV")


if __name__ == "__main__":
    main()
