#!/usr/bin/env python3

import argparse

from pymatgen.io.vasp import Vasprun

from lib import get_vasprun, show_nonconvergence_warning


def main(vasprun: Vasprun):
    show_nonconvergence_warning(vasprun)
    print(f"Total energy: {vasprun.final_energy}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Get total energies")
    vasprun = get_vasprun(parser)
    main(vasprun)
