#!/usr/bin/env python3
from pymatgen.io.vasp import Vasprun

from lib import process_vasprun_decorator


@process_vasprun_decorator("Get kpoints")
def main(vasprun: Vasprun):
    print(vasprun.kpoints)


if __name__ == "__main__":
    main()
