#!/usr/bin/env python3

import argparse

from pymatgen.io.vasp import Vasprun

from lib import get_vasprun, show_nonconvergence_warning


def main(vasprun: Vasprun):
    show_nonconvergence_warning(vasprun)
    print(vasprun.kpoints)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Get kpoints")
    vasprun = get_vasprun(parser)
    main(vasprun)
