#!/usr/bin/env python3

import argparse
import os
import sys

from pymatgen.core.structure import Structure
from pymatgen.io.vasp import Poscar


def main():
    # オプション引数を読み込む
    parser = argparse.ArgumentParser(
        description="convert given poscar to primitive cell poscar"
    )
    parser.add_argument("poscar_path", type=str, help="poscar path")
    parser.add_argument(
        "--tolerance",
        type=float,
        default=0.25,
        help="tolerance for finding the primitive cell (default: 0.25)",
    )
    args = parser.parse_args()
    poscar_path: str = args.poscar_path
    tolerance: float = args.tolerance

    # poscar_pathの存在を確認する
    if not os.path.exists(poscar_path):
        raise FileNotFoundError(f"{poscar_path} not found.")

    # poscarを読み込む
    try:
        structure = Structure.from_file(poscar_path)
    except Exception as e:
        raise RuntimeError(f"Failed to read {poscar_path}: {e}")

    # ユニットセルに変換する
    primitive_structure = structure.get_primitive_structure(tolerance=tolerance)

    # 既に単位胞ならば何もしない
    if structure.num_sites == primitive_structure.num_sites:
        print(f"{poscar_path} is already primitive cell.")
        print("Exiting ...")
        sys.exit(0)

    # poscarファイルとして保存する
    base, ext = os.path.splitext(os.path.basename(poscar_path))
    output_path = f"{base}_prim"
    if ext:
        output_path += "." + ext
    poscar = Poscar(primitive_structure)
    poscar.write_file(output_path)


if __name__ == "__main__":
    main()
