#!/usr/bin/env python3

import argparse

from pymatgen.io.vasp import Vasprun

from lib import get_bandgap, get_vasprun, show_nonconvergence_warning


def main(vasprun: Vasprun):
    show_nonconvergence_warning(vasprun)
    bandgap = get_bandgap(vasprun)
    print(f"Bandgap: {bandgap} eV")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Get total energies")
    vasprun = get_vasprun(parser)
    main(vasprun)
