#!/usr/bin/env python3

import argparse
import os
import sys

import numpy as np
from pymatgen.core.structure import Structure
from pymatgen.io.vasp import Poscar

from lib import get_pymatgen_structure


def main():
    # オプション引数を読み込む
    parser = argparse.ArgumentParser(
        description="convert given poscar to supercell poscar"
    )
    parser.add_argument("poscar_path", type=str, help="POSCAR filepath", required=True)
    parser.add_argument(
        "--size",
        type=int,
        nargs=3,
        required=True,
        metavar=("a", "b", "c"),
        help="supercell size as 3 integers for a, b, c dimensions",
    )
    args = parser.parse_args()
    poscar_path: str = args.poscar_path
    size: tuple[int, int, int] = args.sizes

    # スーパーセルを生成
    structure = get_pymatgen_structure(poscar_path)
    supercell_structure = structure.make_supercell(np.diag(size), in_place=False)

    # POSCARファイルとしてスーパーセルを保存
    poscar = Poscar(supercell_structure)
    base, ext = os.path.splitext(os.path.basename(poscar_path))
    output_path = f"{base}_supercell_{size[0]}x{size[1]}x{size[2]}{ext}"
    print(f"Writing out supercell structure to {output_path} ...")
    poscar.write_file(output_path)


if __name__ == "__main__":
    main()
