#!/usr/bin/env python3

import argparse
import os
import re
import shutil
import subprocess
import sys
from glob import glob


def main():
    # オプション引数を読み込む
    parser = argparse.ArgumentParser(description="open neb structures")
    parser.add_argument(
        "--directory",
        type=str,
        default="./",
        help="neb caculation root directory",
    )


if __name__ == "__main__":
    main()
